config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, sign_out_via: [:get, :delete]

  constraints(subdomain: "admin") do
    devise_for :administrators, path: :administrator, controllers: {
      sessions: 'administrator/sessions'
    }, sign_out_via: [:get, :delete]

    devise_scope :administrator do
      namespace :administrator do
        post 'sign_in/new_challenge', to: 'sessions#new_challenge', as: :new_session_challenge

        resources :emergency_passkey_registrations, only: [:new, :create, :show] do
          member do
            patch :use
            post :new_challenge
          end
        end
      end

      authenticated :administrator do
        mount Flipper::UI.app(Flipper) => '/flipper'
        mount GoodJob::Engine => 'good_job'
        root to: "admin/organizations#index", as: :admin_root

        namespace(:admin) do
          resources :organizations
          namespace(:organization) do
            resources :attachments
            resources :jobs
            resources :notes
                  end

          resources :users
          namespace(:user) do
            resources :emergency_passkey_registrations
            resources :passkeys
          end

          namespace(:utility) do
            resources :ip_addresses
            resources :user_agents
          end

          resources :google_places
          resources :memberships
          resources :membership_invitations
        end
      end
    end

    get '/manifest.webmanifest' => "web_manifest#admin_manifest", as: :admin_web_manifest

    match '/*glob', to: redirect('/404'), via: :all
  end

  devise_scope :user do
    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    authenticated(:user) do
      post('reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge',
                                           as: :new_user_reauthentication_challenge
          )
      post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication
    end

    namespace :users, as: :user do
      get 'emergency_login/:id', to: 'sessions#emergency_login', as: :emergency_login

      authenticated(:user) do
        resources :passkeys, only: [:create, :destroy] do
          collection do
            post :new_create_challenge
          end

          member do
            post :new_destroy_challenge
          end
        end

        patch :update_theme, to: "theme#update"

        resources :memberships, only: [:index, :update]
        delete "membership_invitations/:id", to: "membership_invitations#destroy", as: :hide_membership_invitation
      end

      resources :emergency_passkey_registrations, only: [:new, :create, :show] do
        member do
          patch :use
          post :new_challenge
        end
      end
    end
  end

  resources :membership_invitations, only: [:show] do
    member do
      post :new_create_challenge
      post :create_user_and_use
      delete :sign_out_then_show

      authenticated(:user) do
        patch :accept_as_current_user
      end
    end
  end

  resources :organizations, only: [:index, :show] do
    scope module: 'organizations' do
      resources :membership_invitations, only: [:destroy] do
        member do
          patch :resend
        end
      end
      resources :memberships, only: [:index, :create, :edit, :update, :destroy]

      resources :attachments, only: [:create]

      resources :jobs do
        resources :onsites, shallow: true, shallow_path: "/organizations/:organization_id", except: [:index, :destroy]
        resources :tasks, controller: "job_tasks", only: [:new, :create]
        resources(:job_tasks,
                  shallow: true,
                  shallow_path: "/organizations/:organization_id",
                  except: [:index, :new, :create]
                )
      end

      resources :notes, except: [:new]
      resources :notes, only: [:new], path: "/notes/:resource_gid"
    end
  end

  constraints(subdomain: "readonly") do
    scope module: 'readonly' do
      resources :onsites, only: [:show], as: :readonly_onsite
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "organizations#index"

  get "/application_health/boot" => "application_health#show"
  get "/application_health/db" => "application_health#db"
  get "/application_health/wafris" => "application_health#wafris"

  get '/manifest.webmanifest' => "web_manifest#manifest", as: :web_manifest
end

app/models/membership_invitation.rb
# frozen_string_literal: true

class MembershipInvitation < ApplicationRecord
  class AlreadyUsedError < StandardError; end

  enum :membership_type, Membership.membership_types

  belongs_to :organization
  belongs_to :sender, class_name: "User"
  belongs_to :membership, optional: true
  belongs_to :user, optional: true

  normalizes :email, with: ->(email){ email.strip.downcase }

  validates :email, presence: true, allow_blank: false, uniqueness: {scope: :organization_id}
  validates :membership_type, presence: true, allow_blank: false
  validate :sender_has_membership_in_organization, on: :create

  scope :visible, -> { where(visible: true) }
  scope :unused, -> { where(user: nil) }

  generates_token_for :invitation do
    user_id
  end

  def use_for_and_notify!(user:)
    raise AlreadyUsedError if self.user.present?
    self.user = user
    self.membership = create_membership!
    self.save!
    MembershipInvitationMailer.invitation_accepted(membership_invitation: self).deliver_later
  end

  def create_membership!
    return organization.memberships.create!(
      state: :active,
      user: self.user,
      membership_type: self.membership_type
    )
  end

  def can_be_resent?
    return false if last_sent_at.present? && last_sent_at > 10.minutes.ago
    return false if user.present?
    return false if !visible?

    return true
  end

  protected

  def sender_has_membership_in_organization
    return if organization.blank?
    return if sender.blank?
    return if OrganizationPolicy.new(organization, user: sender).apply(:manage?)
    errors.add(:sender, :cannot_manage_organization)
  end
end

app/controllers/admin/membership_invitations_controller.rb
# frozen_string_literal: true

module Admin
  class MembershipInvitationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/membership_invitations_controller.rb
# frozen_string_literal: true

class MembershipInvitationsController < ApplicationController
  include Warden::WebAuthn::AuthenticationInitiationHelpers
  include Warden::WebAuthn::RegistrationHelpers
  include RelyingParty
  include PracticalFramework::Controllers::CreateUserFromInvitations

  before_action :find_membership_invitation
  before_action :verify_credential_integrity, only: [:create_user_and_use]
  before_action :verify_passkey_challenge, only: [:create_user_and_use]
  before_action :authenticate_user!, only: [:accept_as_current_user]

  skip_verify_authorized

  breadcrumb :membership_invitation, :membership_invitation_path

  layout "app_chrome"

  def show
    store_location_for(:user, membership_invitation_path(params[:id]))

    if !user_signed_in?
      @new_user_form = CreateNewUserWithMembershipInvitationForm.new(user: User.new,
                                                                     membership_invitation: @membership_invitation,
                                                                     email: @membership_invitation.email,
                                                                    )
    end
  end

  def create_user_and_use
    form_params = user_from_invitation_form_params.merge(user: User.new(webauthn_id: registration_user_id),
                                                         membership_invitation: @membership_invitation,
                                                         webauthn_credential: @webauthn_credential
                                                        )
    form = CreateNewUserWithMembershipInvitationForm.new(form_params)
    form.save!

    flash[:notice] = flash_success_with_icon(message: t('membership_invitations.registered_message'))
    json_redirect(location: new_user_session_url)
    store_location_for(:user, organization_url(@membership_invitation.organization))
  rescue ActiveRecord::RecordInvalid
    errors = PracticalFramework::FormBuilders::Base.build_error_json(model: form, helpers: helpers)
    render json: errors, status: :bad_request
  end

  def accept_as_current_user
    @membership_invitation.use_for_and_notify!(user: current_user)
    set_accept_as_current_user_flash
    redirect_to organization_url(@membership_invitation.organization)
  rescue ActiveRecord::RecordInvalid => e
    raise e unless e.record.errors.of_kind?(:user, :taken)
    flash[:alert] = flash_alert_with_icon(message: e.record.errors[:user].join)
    render :show, status: :unprocessable_entity
  end

  def sign_out_then_show
    sign_out(:user)
    redirect_to membership_invitation_url(params[:id])
  end

  protected

  def set_accept_as_current_user_flash
    if using_web_awesome?
      icon = helpers.icon_set.accepted_membership_invitation_icon
    else
      icon = helpers.icon(style: "fa-kit", name: 'solid-warehouse-circle-check')
    end

    message = t('membership_invitations.accepted_message', organization_name: @membership_invitation.organization.name)
    flash[:success] = flash_success_with_icon(message: message, icon: icon)
  end

  def find_membership_invitation
    @membership_invitation = MembershipInvitation.unused.visible.find_by_token_for!(:invitation, params[:id])
  end

  def registration_challenge_key
    "user_from_invitation_creation_challenge"
  end

  def registration_user_id_key
    "user_from_invitation_webauthn_id"
  end

  def user_details_for_registration
    store_registration_user_id
    { id: registration_user_id, name: user_details_params[:email], display_name: user_details_params[:name] }
  end

  def user_details_params
    params.require(:create_new_user_with_membership_invitation_form).permit(:email, :name)
  end

  def user_from_invitation_form_params
    params.require(:create_new_user_with_membership_invitation_form).permit(:email, :name, :passkey_label)
  end

  def passkey_params
    params.require(:create_new_user_with_membership_invitation_form).permit(:passkey_label, :passkey_credential)
  end

  def temporary_form_with_passkey_credential_error(message:)
    temporary_form = CreateNewUserWithMembershipInvitationForm.new
    temporary_form.errors.add(:passkey_credential, message)

    return temporary_form
  end
end

app/controllers/organizations/membership_invitations_controller.rb
# frozen_string_literal: true

class Organizations::MembershipInvitationsController < Organizations::BaseController
  before_action :load_membership_invitation
  before_action :authorize_management
  before_action :authorize_membership_invitation_management

  def resend
    if !@membership_invitation.can_be_resent?
      flash[:alert] = flash_alert_with_icon(message: t("organization_memberships.cannot_be_resent_message"))
      redirect_to organization_memberships_url
      return
    end

    @membership_invitation.update!(last_sent_at: Time.now.utc)
    MembershipInvitationMailer.invitation(membership_invitation: @membership_invitation).deliver_later

    set_invitation_flash_success
    redirect_to organization_memberships_url
  end

  def destroy
    @membership_invitation.destroy

    set_invitation_revoked_flash_alert
    redirect_to organization_memberships_url
  end

  protected

  def set_invitation_flash_success
    if using_web_awesome?
      icon = helpers.icon_set.sent_email_icon
    else
      icon = helpers.sent_email_icon
    end

    message = t('organization_memberships.invitation_sent_message', email: @membership_invitation.email)
    flash[:success] = flash_notice_with_icon(message: message, icon: icon)
  end

  def set_invitation_revoked_flash_alert
    if using_web_awesome?
      icon = helpers.icon_set.remove_link_icon
    else
      icon = helpers.icon(style: "fa-duotone", name: 'link-slash')
    end

    message = t('organization_memberships.invitation_revoked_message', email: @membership_invitation.email)
    flash[:alert] = flash_alert_with_icon(message: message, icon: icon)
  end

  def load_membership_invitation
    @membership_invitation = authorized_scope(current_organization.membership_invitations,
                                              with: Organization::MembershipInvitationPolicy).find(params[:id]
                                            )
  end

  def authorize_management
    authorize!(@current_organization, to: :manage?, with: OrganizationPolicy)
  end

  def authorize_membership_invitation_management
    authorize!(@membership_invitation, to: :manage?, with: Organization::MembershipInvitationPolicy)
  end
end

app/controllers/users/membership_invitations_controller.rb
# frozen_string_literal: true

class Users::MembershipInvitationsController < Users::BaseController
  before_action :load_membership_invitation
  before_action :authorize_management
  before_action :authorize_membership_invitation_management

  def destroy
    @membership_invitation.destroy

    set_flash_alert
    redirect_to user_memberships_url
  end

  protected

  def set_flash_alert
    message = t('user_memberships.invitation_hidden_message',
                organization_name: @membership_invitation.organization.name
              )

    if using_web_awesome?
      icon = helpers.icon_set.destroy_membership_invitation_icon
    else
      icon = helpers.icon(style: "fa-kit", name: 'solid-warehouse-slash')
    end

    flash[:alert] = flash_alert_with_icon(message: message, icon: icon)
  end

  def load_membership_invitation
    @membership_invitation = authorized_scope(current_user.membership_invitations,
                                              with: User::MembershipInvitationPolicy).find(params[:id]
                                            )
  end

  def authorize_management
    authorize!(current_user, to: :manage?, with: UserPolicy)
  end

  def authorize_membership_invitation_management
    authorize!(@membership_invitation, to: :manage?, with: User::MembershipInvitationPolicy)
  end
end

app/helpers/membership_invitations_helper.rb
# frozen_string_literal: true

module MembershipInvitationsHelper
end

app/views/membership_invitations/_accept_as_current_user_prompt.html.erb
<section class="stack-compact">
  <h2><%= t("membership_invitations.accept_form.accept_as_current_user.title", name: current_user.name) %></h2>

  <%= t("membership_invitations.accept_form.accept_as_current_user.description.html", organization_name: membership_invitation.organization.name) %>

  <table>
    <tbody>
      <tr>
        <th class="table-label"><%= email_address_icon %> Email</th>
        <td><%= mail_to current_user.email %></td>
      </tr>
      <tr>
        <th class="table-label"><%= user_name_icon %> Name</th>
        <td><%= current_user.name %></td>
      </tr>
    </tbody>
  </table>

  <section class='cluster-default' style="--justify: space-between; --align: center" role="list">
    <div role="listitem">
      <%= render PracticalFramework::Components::ButtonTo.new(sign_out_then_show_membership_invitation_url(params[:id]), method: :delete) do %>
        <%= sign_out_icon %>
        <%= t('membership_invitations.accept_form.accept_as_current_user.sign_out_button_title') %>
      <% end %>
    </div>
    <div role="listitem">
      <%= render PracticalFramework::Components::ButtonTo.new(accept_as_current_user_membership_invitation_url(params[:id]), method: :patch, class: "success") do %>
        <%= icon(style: 'fa-duotone', name: 'circle-check') %>
        <%= t('membership_invitations.accept_form.accept_as_current_user.accept_button_title') %>
      <% end %>
    </div>
  </section>
</section>

app/views/membership_invitations/_invitation_details.html.erb
<table>
  <caption><%= t("membership_invitations.accept_form.details.caption.html") %></caption>
  <tbody>
    <tr>
      <th class='table-label'><%= warehouse_icon %> Organization</th>
      <td><%= membership_invitation.organization.name %></td>
    </tr>
    <tr>
      <th class='table-label'><%= badge_icon %> Role</th>
      <td>
        <%= membership_type_icon(membership_type: membership_invitation.membership_type) %>
        <%= t("membership_types.#{membership_invitation.membership_type}.human") %>
      </td>
    </tr>
  </tbody>
</table>

app/views/membership_invitations/_new_user_from_invitation_form.html.erb
<%= practical_form_with(
      model: form,
      url: create_user_and_use_membership_invitation_url(params[:id]),
      local: false,
      id: dom_id(form, :registration_form),
      "aria-describedby": dom_id(form, :generic_errors),
      method: :post,
      data: {
        "challenge_url": new_create_challenge_membership_invitation_url(params[:id]),
        "credential_field_name": field_name(form.model_name.param_key, :passkey_credential)
      },
      builder: PracticalFramework::FormBuilders::Base,
      class: "stack-compact"
) do |f| %>
  <%= f.fieldset do %>
    <%= f.legend do %>
      <%= signup_icon %>
      <%= t("user_settings.registration.form.title") %>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :email do %>
        <%= icon(style: 'fa-solid', name: 'at') %>
        Email
      <% end %>

      <%= f.email_field(:email, placeholder: t("practical_framework.forms.placeholders.email"),
                                autofocus: true,
                                autocomplete: "username webauthn",
                                required: true,
                                data: {"focusout-validation": true}
                       )
      %>

      <%= f.field_errors :email %>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :name do %>
        <%= icon(style: 'fa-solid', name: 'hand-wave') %>
        Name
      <% end %>

      <%= f.text_field(:name, placeholder: t("practical_framework.forms.placeholders.name"),
                                autofocus: true,
                                autocomplete: "name",
                                required: true,
                                data: {"focusout-validation": true}
                       )
      %>

      <%= f.field_errors :name %>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :passkey_label do %>
        <%= t("practical_framework.forms.input_label.html", icon: icon(style: "fa-solid", name: "tag"), text: "Passkey label") %>
      <% end %>
      <%= f.text_field :passkey_label, placeholder: "iCloud Keychain", required: true, data: {"focusout-validation": true} %>

      <%= f.field_errors :passkey_label %>
    <% end %>

    <%= f.hidden_field :passkey_credential %>

    <%= f.fallback_error_section(options: {id: dom_id(form, :generic_errors)}) %>

    <section>
      <%= render PracticalFramework::Components::StandardButton.new(title: t("membership_invitations.new_user_from_invitation_form.submit_button_title"), leading_icon: passkey_icon, type: :submit, html_options: {data: {disable: true}}, classes: :success) %>
    </section>
  <% end %>
<% end %>

<script type="module">
  import {submitFormEvent} from 'registration_form'
  document.getElementById(`<%= dom_id(form, :registration_form) %>`).addEventListener('submit', submitFormEvent)
</script>

app/views/membership_invitations/create_user_and_user.html.erb
<h1>MembershipInvitations#create_user_and_user</h1>
<p>Find me in app/views/membership_invitations/create_user_and_user.html.erb</p>

app/views/membership_invitations/show.html+webawesome.erb
<section class="wa-stack">
  <h2><%= icon_text(icon: icon_set.memberships_icon, text: t("membership_invitations.accept_form.title")) %></h2>

  <%= t("membership_invitations.accept_form.description.html") %>

  <section class="wa-cluster">
    <%= render MembershipInvitation::DetailsComponent.new(membership_invitation: @membership_invitation) %>
  </section>

  <% if user_signed_in? %>
    <%= render MembershipInvitation::AcceptAsCurrentUserComponent.new(membership_invitation: @membership_invitation) %>
  <% else %>
    <% content_for(:head) do %>
      <%= javascript_include_tag "v2-register-passkey-form", type: :module %>
    <% end %>
    <section class="wa-stack">
      <%= render Forms::MembershipInvitation::NewUserFromInvitationFormComponent.new(
        form: @new_user_form,
        invitation_id: params[:id]
      ) %>

      <wa-divider></wa-divider>
      <section>
        <%= button_to(new_user_session_url, method: :get) do %>
          <%= icon_text(icon: icon_set.signin_icon, text: t('membership_invitations.new_user_from_invitation_form.signin_button_title')) %>
        <% end %>
      </section>
    </section>
  <% end %>
</section>

app/views/membership_invitations/show.html.erb
<div class="cover">
  <section class="stack-compact center principal">
    <h1>
      <%= icon(style: 'fa-solid fa-fw', name: :hexagon) %>

      <%= t("membership_invitations.accept_form.title") %>
    </h1>
    <%= t("membership_invitations.accept_form.description.html") %>

    <%= render partial: "invitation_details", locals: {membership_invitation: @membership_invitation} %>
    <hr>

    <% if user_signed_in? %>
      <%= render partial: "accept_as_current_user_prompt", locals: {membership_invitation: @membership_invitation} %>
    <% else %>
      <%= render partial: "new_user_from_invitation_form", locals: {form: @new_user_form} %>
      <hr>
      <section>
        <%= render PracticalFramework::Components::ButtonTo.new(new_user_session_url, method: :get) do %>
          <%= signin_icon %>
          <%= t('membership_invitations.new_user_from_invitation_form.signin_button_title') %>
        <% end %>
      </section>
    <% end %>
  </section>
</div>