config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, sign_out_via: [:get, :delete]

  constraints(subdomain: "admin") do
    devise_for :administrators, path: :administrator, controllers: {
      sessions: 'administrator/sessions'
    }, sign_out_via: [:get, :delete]

    devise_scope :administrator do
      namespace :administrator do
        post 'sign_in/new_challenge', to: 'sessions#new_challenge', as: :new_session_challenge

        resources :emergency_passkey_registrations, only: [:new, :create, :show] do
          member do
            patch :use
            post :new_challenge
          end
        end
      end

      authenticated :administrator do
        mount Flipper::UI.app(Flipper) => '/flipper'
        mount GoodJob::Engine => 'good_job'
        root to: "admin/organizations#index", as: :admin_root

        namespace(:admin) do
          resources :organizations
          namespace(:organization) do
            resources :attachments
            resources :jobs
            resources :notes
                  end

          resources :users
          namespace(:user) do
            resources :emergency_passkey_registrations
            resources :passkeys
          end

          namespace(:utility) do
            resources :ip_addresses
            resources :user_agents
          end

          resources :google_places
          resources :memberships
          resources :membership_invitations
        end
      end
    end

    get '/manifest.webmanifest' => "web_manifest#admin_manifest", as: :admin_web_manifest

    match '/*glob', to: redirect('/404'), via: :all
  end

  devise_scope :user do
    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    authenticated(:user) do
      post('reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge',
                                           as: :new_user_reauthentication_challenge
          )
      post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication
    end

    namespace :users, as: :user do
      get 'emergency_login/:id', to: 'sessions#emergency_login', as: :emergency_login

      authenticated(:user) do
        resources :passkeys, only: [:create, :destroy] do
          collection do
            post :new_create_challenge
          end

          member do
            post :new_destroy_challenge
          end
        end

        patch :update_theme, to: "theme#update"

        resources :memberships, only: [:index, :update]
        delete "membership_invitations/:id", to: "membership_invitations#destroy", as: :hide_membership_invitation
      end

      resources :emergency_passkey_registrations, only: [:new, :create, :show] do
        member do
          patch :use
          post :new_challenge
        end
      end
    end
  end

  resources :membership_invitations, only: [:show] do
    member do
      post :new_create_challenge
      post :create_user_and_use
      delete :sign_out_then_show

      authenticated(:user) do
        patch :accept_as_current_user
      end
    end
  end

  resources :organizations, only: [:index, :show] do
    scope module: 'organizations' do
      resources :membership_invitations, only: [:destroy] do
        member do
          patch :resend
        end
      end
      resources :memberships, only: [:index, :create, :edit, :update, :destroy]

      resources :attachments, only: [:create]

      resources :jobs do
        resources :onsites, shallow: true, shallow_path: "/organizations/:organization_id", except: [:index, :destroy]
        resources :tasks, controller: "job_tasks", only: [:new, :create]
        resources(:job_tasks,
                  shallow: true,
                  shallow_path: "/organizations/:organization_id",
                  except: [:index, :new, :create]
                )
      end

      resources :notes, except: [:new]
      resources :notes, only: [:new], path: "/notes/:resource_gid"
    end
  end

  constraints(subdomain: "readonly") do
    scope module: 'readonly' do
      resources :onsites, only: [:show], as: :readonly_onsite
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "organizations#index"

  get "/application_health/boot" => "application_health#show"
  get "/application_health/db" => "application_health#db"
  get "/application_health/wafris" => "application_health#wafris"

  get '/manifest.webmanifest' => "web_manifest#manifest", as: :web_manifest
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_many :membership_invitations, dependent: :destroy
  has_many :memberships, dependent: :destroy, class_name: "::Membership"
  has_many :users, through: :memberships
  has_many :attachments, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :onsites, through: :jobs
  has_many :job_tasks, through: :jobs, source: :tasks
end

app/controllers/admin/organization/attachments_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::AttachmentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/jobs_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::JobsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/notes_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::NotesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/onsites_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::OnsitesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organizations_controller.rb
# frozen_string_literal: true

module Admin
  class OrganizationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/organizations/attachments_controller.rb
# frozen_string_literal: true

class Organizations::AttachmentsController < Organizations::BaseController
  before_action :authorize_creation, only: [:create]
  def create
    attachment = current_organization.attachments.create!(user: current_user, attachment: attachment_params)

    response_payload = {
      url: attachment.attachment.url,
      sgid: attachment.sgid_for_document
    }

    render json: response_payload, status: :created
  end

  protected

  def attachment_params
    params.require(:file)
  end

  def authorize_creation
    authorize!(nil, to: :create?, with: Organization::AttachmentPolicy)
  end
end

app/controllers/organizations/base_controller.rb
# frozen_string_literal: true

class Organizations::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_organization
  before_action :set_webawesome_variant
  authorize :organization, through: :current_organization

  helper_method :current_organization

  protected

  def set_current_organization
    @current_organization = current_user.organizations.find(params[:organization_id])
    authorize!(@current_organization, to: :show?, with: OrganizationPolicy)
  end

  def current_organization
    raise ArgumentError if @current_organization.nil?
    @current_organization
  end
end

app/controllers/organizations/membership_invitations_controller.rb
# frozen_string_literal: true

class Organizations::MembershipInvitationsController < Organizations::BaseController
  before_action :load_membership_invitation
  before_action :authorize_management
  before_action :authorize_membership_invitation_management

  def resend
    if !@membership_invitation.can_be_resent?
      flash[:alert] = flash_alert_with_icon(message: t("organization_memberships.cannot_be_resent_message"))
      redirect_to organization_memberships_url
      return
    end

    @membership_invitation.update!(last_sent_at: Time.now.utc)
    MembershipInvitationMailer.invitation(membership_invitation: @membership_invitation).deliver_later

    set_invitation_flash_success
    redirect_to organization_memberships_url
  end

  def destroy
    @membership_invitation.destroy

    set_invitation_revoked_flash_alert
    redirect_to organization_memberships_url
  end

  protected

  def set_invitation_flash_success
    if using_web_awesome?
      icon = helpers.icon_set.sent_email_icon
    else
      icon = helpers.sent_email_icon
    end

    message = t('organization_memberships.invitation_sent_message', email: @membership_invitation.email)
    flash[:success] = flash_notice_with_icon(message: message, icon: icon)
  end

  def set_invitation_revoked_flash_alert
    if using_web_awesome?
      icon = helpers.icon_set.remove_link_icon
    else
      icon = helpers.icon(style: "fa-duotone", name: 'link-slash')
    end

    message = t('organization_memberships.invitation_revoked_message', email: @membership_invitation.email)
    flash[:alert] = flash_alert_with_icon(message: message, icon: icon)
  end

  def load_membership_invitation
    @membership_invitation = authorized_scope(current_organization.membership_invitations,
                                              with: Organization::MembershipInvitationPolicy).find(params[:id]
                                            )
  end

  def authorize_management
    authorize!(@current_organization, to: :manage?, with: OrganizationPolicy)
  end

  def authorize_membership_invitation_management
    authorize!(@membership_invitation, to: :manage?, with: Organization::MembershipInvitationPolicy)
  end
end

app/views/organizations/jobs/_datatable_form.html.erb
<%# locals: (datatable_form:, url: organization_jobs_url(current_organization)) -%>

<%= render Navigation::DatatableFilterWrapperComponent.new(datatable_params: params["datatable"],
                                                           title: t("dispatcher.jobs.datatable_form.title")
                                                          ) do
%>
  <%= application_form_with(model: datatable_form, scope: :datatable, url: url, local: true, method: :get) do |f| %>
    <%= f.hidden_field :sort_key %>
    <%= f.hidden_field :sort_direction %>
    <%= f.fields_for :filters, datatable_form.filters do |filter_fields| %>
      <%= f.fieldset("aria-required": true, id: f.field_id(:status)) do %>
        <%= f.legend do %>
          <%= status_icon %> Status
          <%= f.field_errors(:status, class: 'visually-hidden', id: f.field_id(:status, :errors_aria)) %>
        <% end %>

        <%= filter_fields.check_box_collection(field_method: :status, options: job_status_options, collection_check_boxes_options: {include_hidden: false}) %>
      <% end %>

      <%= f.input_wrapper do %>
        <%= f.label :name do %>
          <%= job_name_icon %> Name
        <% end %>

        <%= filter_fields.search_field :job_name %>
      <% end %>

      <section>
        <%= render PracticalFramework::Components::StandardButton.new(title: t("dispatcher.datatable.form.submit_button_title"), leading_icon: apply_filters_icon, type: :submit, html_options: {data: {disable: true}}) %>
      </section>
    <% end %>
  <% end %>

<% end %>

app/views/organizations/jobs/_form.html.erb
<%= application_form_with(model: form, url: url_for([form.job, organization_id: current_organization])) do |f| %>
  <%= f.fieldset do %>
    <%= f.legend do %>
      <%= job_icon %>
      <%= t("dispatcher.jobs.form.title") %>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :name do %>
        <%= job_name_icon %> Name
      <% end %>

      <%= f.text_field(:name, placeholder: t("dispatcher.placeholders.job_name"),
        autofocus: true,
        autocomplete: "none",
        required: true,
        data: {"focusout-validation": true}
                       ) %>

      <%= f.field_errors :name %>
    <% end %>

    <%= f.input_wrapper do %>
      <% google_place_popover_id = dom_id(form.job, :google_place_address_confirmation_popover) %>
      <div class="cluster-compact">
        <%= f.label :location do %>
          <%= location_icon %> Address
        <% end %>

        <%= f.google_places_popover_button(google_place_popover_id: google_place_popover_id) %>
      </div>

      <%= f.google_places_autocomplete_field(:google_place, location_field_name: :location, popover_id: google_place_popover_id) %>

      <%= f.field_errors :location %>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :note do %>
        <%= notes_icon %> Notes
      <% end %>

      <%= f.practical_editor_field(:note, direct_upload_url: organization_attachments_url(current_organization)) %>

      <%= f.field_errors :note %>
    <% end %>

    <%= f.fieldset("aria-required": true, id: f.field_id(:status)) do %>
      <%= f.legend do %>
        <%= status_icon %> Status
        <%= f.field_errors(:status, class: 'visually-hidden', id: f.field_id(:status, :errors_aria)) %>
      <% end %>

      <%= f.required_radio_collection_wrapper(:status, "validation-message": form.job.errors.generate_message(:status, :blank), class: "stack-compact") do %>
        <%= f.radio_collection(field_method: :status, options: job_status_options) %>
      <% end %>

      <%= f.field_errors :status, "aria-hidden": true, id: f.field_id(:status, :errors) %>
    <% end %>

    <%= f.fallback_error_section(options: {id: dom_id(form, :generic_errors)}) %>

    <section>
      <%= render PracticalFramework::Components::StandardButton.new(title: t("dispatcher.jobs.form.submit_button_title"), leading_icon: save_icon, type: :submit, html_options: {data: {disable: true}}) %>
    </section>
  <% end %>
<% end %>

app/views/organizations/jobs/_job_table.html.erb
<table class="no-max-inline-size jobs">
  <col class="table-label">
  <col span="3">
  <thead>
    <tr>
      <th class='table-label' scope="col">
        <%= render Navigation::DatatableSortLink.new(
            url: organization_jobs_url(current_organization,
                                       datatable: Navigation::DatatableSortLink.merged_payload(datatable_form: @datatable_form,
                                         sort_key: "name"
                                       )
            ),
            datatable_form: @datatable_form,
            sort_key: "name"
          ) do %>
          <%= job_name_icon %> Job Name
        <% end %>
      </th>
      <th class='table-label' scope="col">
        <%= render Navigation::DatatableSortLink.new(
            url: organization_jobs_url(current_organization,
                                       datatable: Navigation::DatatableSortLink.merged_payload(datatable_form: @datatable_form,
                                         sort_key: "status"
                                       )
            ),
            datatable_form: @datatable_form,
            sort_key: "status"
          ) do %>
          <%= status_icon %> Status
        <% end %>
      </th>
      <th class='table-label' scope="col">
        <%= job_task_icon %> Tasks
      </th>
      <th class='table-label' scope="col">
        <%= onsite_icon %> Onsites
      </th>
    </tr>
  </thead>

  <tbody>
  <%= render partial: "job_table_row", collection: jobs, as: :job %>
  </tbody>
</table>

app/views/organizations/jobs/_job_table_row.html.erb
<tr>
  <td>
    <%= link_to organization_job_url(current_organization, job) do %>
      <%= job.name %>
    <% end %>
  </td>

  <td>
    <%= render Organization::JobStatusBadge.new(job: job) %>
  </td>

  <td>
    <% cache([job, job.tasks_and_onsites_updated_at, :task_summary_component]) do %>
      <%= render Organization::JobTasks::SummaryComponent.new(job_tasks: job.tasks) %>
    <% end %>
  </td>

  <td>
    <% cache([job, job.tasks_and_onsites_updated_at, :onsites_summary_component]) do %>
      <%= render Organization::Jobs::OnsitesSummaryComponent.new(job: job) %>
    <% end %>
  </td>
</tr>

app/views/organizations/jobs/edit.html+webawesome.erb
<section class="wa-stack">
  <h2><%= icon_text(icon: icon_set.edit_job_icon, text: t('dispatcher.jobs.edit_job.title')) %></h2>
  <%= render Forms::JobFormComponent.new(form: @form) %>
</section>

app/views/organizations/jobs/edit.html.erb
<section class="stack-default">
  <h1><%= edit_job_icon %> <%= t('dispatcher.jobs.edit_job.title') %></h1>

  <%= render partial: "form", locals: { form: @form }%>
</section>

app/views/organizations/jobs/index.html+webawesome.erb
<section class="wa-stack">
  <%= render Organization::Job::DatatableComponent.new(
      datatable_form: @datatable_form,
      jobs: @organization_jobs,
      pagy: @pagy,
      request: request
    )
  %>
</section>

app/views/organizations/jobs/index.html.erb
<section class="stack-default">
  <h1><%= job_icon %> <%= t("dispatcher.jobs.title") %></h1>

  <nav class="cluster-compact">
    <%= link_to new_organization_job_path do %>
      <%= add_job_icon %> <%= t("dispatcher.jobs.new_job.link_title") %>
    <% end %>
  </nav>

  <%= render Organization::JobsDatatableComponent.new(
    datatable_form: @datatable_form,
    jobs: @organization_jobs,
    pagy: @pagy,
    request: request
  ) %>
</section>

app/views/organizations/jobs/new.html+webawesome.erb
<section class="wa-stack">
  <h2><%= icon_text(icon: icon_set.add_job_icon, text: t('dispatcher.jobs.new_job.title')) %></h2>

  <%= render Forms::JobFormComponent.new(form: @form) %>
</section>

app/views/organizations/jobs/new.html.erb
<section class="stack-default">
  <h1><%= add_job_icon %> <%= t('dispatcher.jobs.new_job.title') %></h1>

  <%= render partial: "form", locals: { form: @form }%>
</section>

app/views/organizations/jobs/show.html+webawesome.erb
<section class="wa-stack">
  <%= render Organization::Job::DetailsComponent.new(job: @organization_job) %>

  <section class="wa-stack">
    <h3><%= icon_text(icon: icon_set.onsite_icon, text: "Onsites") %></h3>

    <nav class="wa-cluster">
      <section>
        <%= link_to(new_organization_job_onsite_url(current_organization, @organization_job), class: "wa-button wa-success") do %>
          <%= icon_text(icon: icon_set.add_onsite_icon, text: t("dispatcher.onsites.new_onsite.link_title")) %>
        <% end %>
      </section>
    </nav>

    <% if @organization_job.onsites.any? %>
      <%= render Organization::Onsite::TableComponent.new(onsites: @organization_job.onsites) %>
    <% else %>
      <%= render Organization::Job::NoOnsitesComponent.new(job: @organization_job) %>
    <% end %>
  </section>

  <section class="wa-stack">
    <h3><%= icon_text(icon: icon_set.job_task_icon, text: "Job Tasks") %></h3>

    <% if @job_tasks.any? %>
      <%= render Organization::JobTask::Datatable::JobComponent.new(
        organization_job: @organization_job,
        datatable_form: @job_task_datatable_form,
        job_tasks: @job_tasks,
        pagy: @pagy,
        request: request
      ) do |component| %>
        <% component.with_add_job_task_dialog_button do %>
          <%= render Organization::JobTask::AddDialogComponent.new(form: @job_task_form) %>
        <% end %>
      <% end %>
    <% else %>
      <%= render Organization::Job::NoTasksComponent.new(job_task_form: @job_task_form) %>
    <% end %>
  </section>
</section>

app/views/organizations/jobs/show.html.erb
<section class="stack-default">
  <header class='cluster-default'>
    <h1>
      <%= job_icon %> <%= @organization_job.name %>
    </h1>

    <section>
      <%= render Organization::JobStatusBadge.new(job: @organization_job) %>
    </section>
  </header>

  <nav class="cluster-compact">
    <%= link_to edit_organization_job_url(current_organization, @organization_job) do %>
      <%= edit_job_icon %> <%= t("dispatcher.jobs.edit_job.link_title") %>
    <% end %>
  </nav>

  <% if @organization_job.google_place.present? %>
    <section class="stack-compact">
      <h2><%= location_icon %> Address</h2>

      <section class='rounded box-compact stack-compact'>
        <%= render GooglePlaceComponent.new(google_place: @organization_job.google_place) %>
      </section>
    </section>
  <% end %>

  <% if @organization_job.note.present? %>
    <section class="stack-compact">
      <h2><%= notes_icon %> Notes</h2>

      <section class='rounded box-compact stack-compact'>
        <%= render Organization::NoteComponent.new(note: @organization_job.note) %>
      </section>
    </section>
  <% end %>

  <section class="stack-compact">
    <h2><%= onsite_icon %> Onsites</h2>

    <nav class="cluster-compact">
      <%= link_to new_organization_job_onsite_url(current_organization, @organization_job) do %>
        <%= add_onsite_icon %> <%= t("dispatcher.onsites.new_onsite.link_title") %>
      <% end %>
    </nav>

    <section>
      <%= render partial: "organizations/onsites/onsite_table", locals: {onsites: @organization_job.onsites} %>
    </section>
  </section>

  <section class="stack-compact">
    <h2><%= job_task_icon %> <%= t('dispatcher.job_tasks.categories.all_tasks.title') %></h2>

    <p><%= t('dispatcher.job_tasks.categories.all_tasks.description') %></p>

    <%= render Organization::Jobs::TasksDatatableComponent.new(
      organization_job: @organization_job,
      datatable_form: @job_task_datatable_form,
      job_tasks: @job_tasks,
      pagy: @pagy,
      request: request
    ) %>

    <details class="box-compact stack-compact rounded" open>
      <summary>
        <h3><%= details_icon %> <span> <%= add_job_task_icon %> <%= t("dispatcher.job_tasks.job_add_task_section.title") %></span></h3>
      </summary>

      <div class="details-contents">
        <section class="add-task-form stack-compact">
          <%= render partial: "organizations/job_tasks/form", locals: {form: @job_task_form, autofocus: false} %>
        </section>
      </div>
    </details>
  </section>
</section>