config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, sign_out_via: [:get, :delete]

  constraints(subdomain: "admin") do
    devise_for :administrators, path: :administrator, controllers: {
      sessions: 'administrator/sessions'
    }, sign_out_via: [:get, :delete]

    devise_scope :administrator do
      namespace :administrator do
        post 'sign_in/new_challenge', to: 'sessions#new_challenge', as: :new_session_challenge

        resources :emergency_passkey_registrations, only: [:new, :create, :show] do
          member do
            patch :use
            post :new_challenge
          end
        end
      end

      authenticated :administrator do
        mount Flipper::UI.app(Flipper) => '/flipper'
        mount GoodJob::Engine => 'good_job'
        root to: "admin/organizations#index", as: :admin_root

        namespace(:admin) do
          resources :organizations
          namespace(:organization) do
            resources :attachments
            resources :jobs
            resources :notes
                  end

          resources :users
          namespace(:user) do
            resources :emergency_passkey_registrations
            resources :passkeys
          end

          namespace(:utility) do
            resources :ip_addresses
            resources :user_agents
          end

          resources :google_places
          resources :memberships
          resources :membership_invitations
        end
      end
    end

    get '/manifest.webmanifest' => "web_manifest#admin_manifest", as: :admin_web_manifest

    match '/*glob', to: redirect('/404'), via: :all
  end

  devise_scope :user do
    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/sessions#new_challenge', as: :new_user_session_challenge

    authenticated(:user) do
      post('reauthenticate/new_challenge', to: 'users/reauthentication#new_challenge',
                                           as: :new_user_reauthentication_challenge
          )
      post 'reauthenticate', to: 'users/reauthentication#reauthenticate', as: :user_reauthentication
    end

    namespace :users, as: :user do
      get 'emergency_login/:id', to: 'sessions#emergency_login', as: :emergency_login

      authenticated(:user) do
        resources :passkeys, only: [:create, :destroy] do
          collection do
            post :new_create_challenge
          end

          member do
            post :new_destroy_challenge
          end
        end

        patch :update_theme, to: "theme#update"

        resources :memberships, only: [:index, :update]
        delete "membership_invitations/:id", to: "membership_invitations#destroy", as: :hide_membership_invitation
      end

      resources :emergency_passkey_registrations, only: [:new, :create, :show] do
        member do
          patch :use
          post :new_challenge
        end
      end
    end
  end

  resources :membership_invitations, only: [:show] do
    member do
      post :new_create_challenge
      post :create_user_and_use
      delete :sign_out_then_show

      authenticated(:user) do
        patch :accept_as_current_user
      end
    end
  end

  resources :organizations, only: [:index, :show] do
    scope module: 'organizations' do
      resources :membership_invitations, only: [:destroy] do
        member do
          patch :resend
        end
      end
      resources :memberships, only: [:index, :create, :edit, :update, :destroy]

      resources :attachments, only: [:create]

      resources :jobs do
        resources :onsites, shallow: true, shallow_path: "/organizations/:organization_id", except: [:index, :destroy]
        resources :tasks, controller: "job_tasks", only: [:new, :create]
        resources(:job_tasks,
                  shallow: true,
                  shallow_path: "/organizations/:organization_id",
                  except: [:index, :new, :create]
                )
      end

      resources :notes, except: [:new]
      resources :notes, only: [:new], path: "/notes/:resource_gid"
    end
  end

  constraints(subdomain: "readonly") do
    scope module: 'readonly' do
      resources :onsites, only: [:show], as: :readonly_onsite
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "organizations#index"

  get "/application_health/boot" => "application_health#show"
  get "/application_health/db" => "application_health#db"
  get "/application_health/wafris" => "application_health#wafris"

  get '/manifest.webmanifest' => "web_manifest#manifest", as: :web_manifest
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_many :membership_invitations, dependent: :destroy
  has_many :memberships, dependent: :destroy, class_name: "::Membership"
  has_many :users, through: :memberships
  has_many :attachments, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :onsites, through: :jobs
  has_many :job_tasks, through: :jobs, source: :tasks
end

app/controllers/admin/organization/attachments_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::AttachmentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/jobs_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::JobsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/notes_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::NotesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organization/onsites_controller.rb
# frozen_string_literal: true

module Admin
  class Organization::OnsitesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/organizations_controller.rb
# frozen_string_literal: true

module Admin
  class OrganizationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/organizations/attachments_controller.rb
# frozen_string_literal: true

class Organizations::AttachmentsController < Organizations::BaseController
  before_action :authorize_creation, only: [:create]
  def create
    attachment = current_organization.attachments.create!(user: current_user, attachment: attachment_params)

    response_payload = {
      url: attachment.attachment.url,
      sgid: attachment.sgid_for_document
    }

    render json: response_payload, status: :created
  end

  protected

  def attachment_params
    params.require(:file)
  end

  def authorize_creation
    authorize!(nil, to: :create?, with: Organization::AttachmentPolicy)
  end
end

app/controllers/organizations/base_controller.rb
# frozen_string_literal: true

class Organizations::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_organization
  before_action :set_webawesome_variant
  authorize :organization, through: :current_organization

  helper_method :current_organization

  protected

  def set_current_organization
    @current_organization = current_user.organizations.find(params[:organization_id])
    authorize!(@current_organization, to: :show?, with: OrganizationPolicy)
  end

  def current_organization
    raise ArgumentError if @current_organization.nil?
    @current_organization
  end
end

app/controllers/organizations/membership_invitations_controller.rb
# frozen_string_literal: true

class Organizations::MembershipInvitationsController < Organizations::BaseController
  before_action :load_membership_invitation
  before_action :authorize_management
  before_action :authorize_membership_invitation_management

  def resend
    if !@membership_invitation.can_be_resent?
      flash[:alert] = flash_alert_with_icon(message: t("organization_memberships.cannot_be_resent_message"))
      redirect_to organization_memberships_url
      return
    end

    @membership_invitation.update!(last_sent_at: Time.now.utc)
    MembershipInvitationMailer.invitation(membership_invitation: @membership_invitation).deliver_later

    set_invitation_flash_success
    redirect_to organization_memberships_url
  end

  def destroy
    @membership_invitation.destroy

    set_invitation_revoked_flash_alert
    redirect_to organization_memberships_url
  end

  protected

  def set_invitation_flash_success
    if using_web_awesome?
      icon = helpers.icon_set.sent_email_icon
    else
      icon = helpers.sent_email_icon
    end

    message = t('organization_memberships.invitation_sent_message', email: @membership_invitation.email)
    flash[:success] = flash_notice_with_icon(message: message, icon: icon)
  end

  def set_invitation_revoked_flash_alert
    if using_web_awesome?
      icon = helpers.icon_set.remove_link_icon
    else
      icon = helpers.icon(style: "fa-duotone", name: 'link-slash')
    end

    message = t('organization_memberships.invitation_revoked_message', email: @membership_invitation.email)
    flash[:alert] = flash_alert_with_icon(message: message, icon: icon)
  end

  def load_membership_invitation
    @membership_invitation = authorized_scope(current_organization.membership_invitations,
                                              with: Organization::MembershipInvitationPolicy).find(params[:id]
                                            )
  end

  def authorize_management
    authorize!(@current_organization, to: :manage?, with: OrganizationPolicy)
  end

  def authorize_membership_invitation_management
    authorize!(@membership_invitation, to: :manage?, with: Organization::MembershipInvitationPolicy)
  end
end

app/views/organizations/notes/_actions.html.erb
<nav class="note-actions">
  <ul class="cluster-default">
    <li>
      <%= link_to edit_organization_note_url(current_organization, note) do %>
        <%= edit_note_icon %> <%= t("dispatcher.notes.edit_note.link_title") %>
      <% end %>
    </li>

    <li>
      <%= render PracticalFramework::Components::ButtonTo.new( organization_note_url(current_organization, note), method: :delete, class: 'danger', data: {confirm: t("dispatcher.notes.delete_note.confirmation_message") }) do %>
          <%= delete_note_icon %>
          <%= t("dispatcher.notes.delete_note.link_title") %>
        <% end %>
    </li>
  </ul>
</nav>

app/views/organizations/notes/_form.html.erb
<%# locals: (form:, show_resource_title: false) -%>

<%= application_form_with(model: form, url: url_for([form.note, organization_id: current_organization])) do |f| %>
  <%= f.fieldset do %>
    <% unless form.persisted? %>
      <%= f.legend do %>
        <%= add_note_icon %>
        <%= t("dispatcher.notes.form.title") %>
      <% end %>
    <% end %>

    <% if show_resource_title %>
      <dl>
        <dt>For</dt>
        <dd><%= note_resource_icon(note: form.note) %> <%= note_resource_title(note: form.note) %></dd>
      </dl>
    <% end %>

    <%= f.input_wrapper do %>
      <%= f.label :tiptap_document do %>
        <%= notes_icon %> Notes
      <% end %>

      <%= f.practical_editor_field(:tiptap_document, direct_upload_url: organization_attachments_url(current_organization)) %>

      <%= f.field_errors :tiptap_document %>
    <% end %>

    <%= f.fallback_error_section(options: {id: dom_id(form, :generic_errors)}) %>

    <% unless form.persisted? %>
      <%= f.hidden_field :resource_gid %>
    <% end %>

    <section>
      <%= render PracticalFramework::Components::StandardButton.new(title: t("dispatcher.notes.form.submit_button_title"), leading_icon: save_icon, type: :submit, html_options: {data: {disable: true}}) %>
    </section>
  <% end %>
<% end %>

app/views/organizations/notes/_note_list_item.html.erb
<%# locals: (note:, show_resource_title: false, show_edit_links: true) -%>

<section id="<%= dom_id(note) %>" class='rounded box-compact stack-compact note-list-item' role="listitem">
  <% if show_resource_title %>
    <%= render Organization::NoteResourceTitleComponent.new(note: note) %>
    <hr>
  <% end %>
  <%= render Organization::NoteComponent.new(note: note) %>

  <% if show_edit_links %>
    <%= render partial: "organizations/notes/actions", locals: {note: note} %>
  <% end %>
</section>

app/views/organizations/notes/_notes_list.html.erb
<section class="stack-default" role="list">
  <%= render partial: "organizations/notes/note_list_item", collection: notes, as: :note, locals: {show_resource_title: true} %>
</section>

app/views/organizations/notes/edit.html+webawesome.erb
<section class="wa-stack">
  <header class="wa-cluster">
    <h2><%= icon_text(icon: icon_set.edit_note_icon, text: t('dispatcher.notes.edit_note.title')) %></h2>

    <section class="wa-callout wa-neutral wa-outlined wa-size-s">
      <%= render Organization::Note::ResourceLinkComponent.new(note: @form.note) %>
    </section>
  </header>

  <section class="note-form">
    <%= render Forms::NoteFormComponent.new(form: @form) %>
  </section>
</section>

app/views/organizations/notes/edit.html.erb
<section class="stack-default">
  <h1><%= edit_note_icon %> <%= t('dispatcher.notes.edit_note.title') %></h1>

  <%= render partial: "form", locals: { form: @form }%>
</section>

app/views/organizations/notes/index.html+webawesome.erb
<section class="wa-stack">
  <h2><%= icon_text(icon: icon_set.notes_icon, text: t("dispatcher.notes.title")) %></h2>

  <section class="wa-stack" role="list">
    <% @organization_notes.each do |note| %>
      <%= render V2::Organization::NoteComponent.new(note: note) do |component| %>
        <% component.with_resource_link do %>
          <%= render Organization::Note::ResourceLinkComponent.new(note: note) %>
        <% end %>

        <% component.with_actions do %>
          <section class="wa-size-s wa-split">
            <%= link_to edit_organization_note_url(current_organization, note), class: "wa-button" do %>
              <%= icon_text(icon: icon_set.notes_icon, text: t("dispatcher.notes.edit_note.link_title")) %>
            <% end %>

            <%= button_to(organization_note_url(current_organization, note), method: :delete, class: 'wa-danger', data: {confirm: t("dispatcher.notes.delete_note.confirmation_message") }) do %>
              <%= icon_text(icon: icon_set.delete_note_icon, text: t("dispatcher.notes.delete_note.link_title")) %>
            <% end %>
          </section>
        <% end %>
      <% end %>
    <% end %>
  </section>
</section>

app/views/organizations/notes/index.html.erb
<section class="stack-default">
  <h1><%= note_icon %> <%= t("dispatcher.notes.title") %></h1>

  <section>
    <%= render partial: "notes_list", locals: {notes: @organization_notes} %>
  </section>
</section>

app/views/organizations/notes/new.html.erb
<section class="stack-default">
  <h1><%= add_note_icon %> <%= t('dispatcher.notes.new_note.title') %></h1>

  <%= render partial: "form", locals: { form: @form, show_resource_title: true }%>
</section>

app/views/organizations/notes/show.html.erb
<section class="stack-default">
  <header class='cluster-default'>
    <h1>
      <%= note_icon %> Note
    </h1>
  </header>

  <%= render partial: "actions", locals: {note: @organization_note} %>

  <section class='rounded box-compact stack-compact'>
    <%= render Organization::NoteResourceTitleComponent.new(note: @organization_note) %>

    <%= render Organization::NoteComponent.new(note: @organization_note) %>
  </section>
</section>